spring.application.name=zuul-gateway
server.port=9527

eureka.client.service-url.defaultZone=http://localhost:7001/eureka
# 屏蔽原路径的访问，另：zuul.ignored-services="*"可以屏蔽所有原名称
# zuul.ignored-services=user-consumer

# 公共前缀
#zuul.prefix=/

# 设置代理的访问名
zuul.routes.user.service-id=user-consumer
zuul.routes.user.path=/api/**

