spring.application.name=spring-cloud-config



# 仓库地址
spring.cloud.config.server.git.uri=
# 分支
spring.cloud.config.label=master
# 查找路径
spring.cloud.config.server.git.search-paths=

# Git用户名密码
spring.cloud.config.server.git.username=
spring.cloud.config.server.git.password=

eureka.client.service-url.defaultZone=http://localhost:7001/eureka


spring.zipkin.base-url=http://localhost:9411