spring.application.name=admin

spring.zipkin.base-url=127.0.0.1:9411

server.port=8090

management.endpoint.health.show-details=always

management.endpoints.web.exposure.include=health,info

eureka.client.service-url.defaultZone=http://localhost:7001/eureka
