# 全部放进配置中心服务器

#spring.application.name=user-provider
#server.port=84
#eureka.client.service-url.defaultZone=http://localhost:7001/eureka
#spring.zipkin.base-url=http://localhost:9411
#spring.boot.admin.client.url=http://127.0.0.1:8090
        